# Generated by Django 2.1.7 on 2019-04-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vk', models.TextField(max_length=50)),
                ('date', models.TextField()),
                ('operation', models.TextField(max_length=50)),
                ('value', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vkuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vk', models.TextField(max_length=50)),
                ('budget', models.TextField(max_length=100)),
                ('pay_day', models.TextField()),
                ('common', models.TextField(max_length=1000)),
                ('fun', models.TextField(max_length=1000)),
                ('invest', models.TextField(max_length=1000)),
                ('days_to_payday', models.TextField(max_length=100)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.History')),
            ],
        ),
    ]
