# Generated by Django 2.1.7 on 2019-04-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_id',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
