# Generated by Django 2.1.7 on 2019-04-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_history_history_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_id',
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='history',
        ),
    ]
