# Generated by Django 2.1.7 on 2019-04-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190403_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type_costs',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
