# Generated by Django 2.1.7 on 2019-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_history_type_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='register_date',
            field=models.TextField(default='07.04.2019', max_length=100),
            preserve_default=False,
        ),
    ]
