# Generated by Django 2.1.7 on 2019-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_vkuser_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='budget',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='days_to_payday',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='pay_day',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='register_date',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
