# Generated by Django 2.1.7 on 2019-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190826_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='is_tutorial_done',
            field=models.BooleanField(default=True),
        ),
    ]
