# Generated by Django 2.1.7 on 2019-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_vkuser_is_tutorial_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='is_tutorial_done',
            field=models.BooleanField(default=False),
        ),
    ]
