# Generated by Django 2.1.7 on 2019-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190826_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkuser',
            name='sure_name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
