# Generated by Django 2.1.7 on 2019-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20190903_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='sure_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
