# Generated by Django 2.1.7 on 2019-10-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20191004_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='timezone',
            field=models.TextField(default=3, max_length=2),
            preserve_default=False,
        ),
    ]
