# Generated by Django 2.1.7 on 2019-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_vkuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
