# Generated by Django 2.1.7 on 2019-11-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20191026_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='comment',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
