# Generated by Django 2.1.7 on 2019-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_history_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='isCostumDarkTheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='isVkTheme',
            field=models.BooleanField(default=True),
        ),
    ]
