# Generated by Django 2.1.7 on 2019-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20191120_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='is_full_history',
            field=models.BooleanField(default=True),
        ),
    ]
