# Generated by Django 2.1.7 on 2019-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_vkuser_is_full_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='currency',
            field=models.TextField(blank=True, default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='currency',
            field=models.TextField(blank=True, default='RUB', max_length=3),
        ),
    ]
